<?php

namespace App\Http\Resources\V1;

use Max\Utils\Resources\JsonResource;

class NoteResource extends JsonResource
{
    public function toArray(): array
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
