<?php
return array (
    'App\\Http\\Controllers\\Api\\V1\\AuthController'    => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Controllers_Api_V1_AuthController_Proxy.php',
    'App\\Http\\Controllers\\Api\\V1\\ChatController'    => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Controllers_Api_V1_ChatController_Proxy.php',
    'App\\Http\\Controllers\\Api\\V1\\CommentController' => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Controllers_Api_V1_CommentController_Proxy.php',
    'App\\Http\\Controllers\\Api\\V1\\NoteController'    => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Controllers_Api_V1_NoteController_Proxy.php',
    'App\\Http\\Controllers\\ApiController'              => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Controllers_ApiBaseController_Proxy.php',
    'App\\Http\\Controllers\\Auth\\IndexBaseController'  => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Controllers_Auth_IndexBaseController_Proxy.php',
    'App\\Http\\Controllers\\BaseController'             => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Controllers_BaseController_Proxy.php',
    'App\\Http\\Controllers\\Index\\BookController'      => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Controllers_Index_BookBaseController_Proxy.php',
    'App\\Http\\Controllers\\Index\\IndexController'     => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Controllers_Index_IndexBaseController_Proxy.php',
    'App\\Http\\Controllers\\Index\\NoteController'      => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Controllers_Index_NoteBaseController_Proxy.php',
    'App\\Http\\Middlewares\\Authentication'             => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Middlewares_Authentication_Proxy.php',
    'App\\Http\\Middlewares\\ExceptionHandlerMiddleware' => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Middlewares_ExceptionHandlerMiddleware_Proxy.php',
    'App\\Http\\Middlewares\\RateLimit'                  => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Middlewares_RateLimit_Proxy.php',
    'App\\Http\\Middlewares\\Statistic'                  => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Middlewares_Statistic_Proxy.php',
    'App\\Http\\Middlewares\\TencentCaptchaMiddleware'   => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Http_Middlewares_TencentCaptchaMiddleware_Proxy.php',
    'App\\Listeners\\DatabaseQueryListener'              => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Listeners_DatabaseQueryListener_Proxy.php',
    'App\\Listeners\\ServerListener'                     => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Listeners_ServerListener_Proxy.php',
    'App\\Model\\Dao\\CommentDao'                        => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Model_Dao_CommentDao_Proxy.php',
    'App\\Model\\Dao\\HeartDao'                          => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Model_Dao_HeartDao_Proxy.php',
    'App\\Model\\Dao\\NoteDao'                           => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Model_Dao_NoteDao_Proxy.php',
    'App\\Services\\Jwt' => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Services_Jwt_Proxy.php',
    'App\\Services\\TencentCloud\\User' => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Services_TencentCloud_User_Proxy.php',
    'App\\Services\\WebSocket\\ChatRoomHandler' => '/mnt/d/Workspace/Self/max-note/bin/../runtime/aop/proxy/App_Services_WebSocket_ChatRoomHandler_Proxy.php',
);
